---
###############################################################################
# The purpose of this file is for automated testing of dotfiles installation, #
# workstation setup, and updating. It'ss not meant for testing .bash_profile  #                                         #
###############################################################################
language: bash
sudo: required
matrix:
  include:
    - os: linux
      dist: debian
      # sudo: required
      services: docker
    - os: osx
      osx_image: xcode9.2
      sudo: required

# OPTIONAL Install apt addons
# OPTIONAL Install cache components
env:
  - TRAVIS_CI_RUN=true GIT_SSH='ssh -o StrictHostKeyChecking=no' GIT_AUTHOR_NAME='Travis CI' GIT_AUTHOR_EMAIL='travis@example.com'
# before_install
install: true
# before_script
script:
  - bash home/.bootstrap.sh
  - bash home/.workstation_setup.sh # in case the trigger (hash git) doesn't trip in .bashrc
  - bsah home/.workstation_update.sh
# OPTIONAL before_cache (for cleaning up cache)

notifications:
  email:
    on_failure: always
    on_success: never
  # slack: https://docs.travis-ci.com/user/notifications/#Configuring-Slack-notifications
    # secure: a;lsdkjf;lasdkfj
# after_success
# after_failure: email ${TRAVIS_TEST_RESULT}
# OPTIONAL before_deploy
# OPTIONAL deploy
# OPTIONAL after_deploy
after_script: true
