---
###############################################################################
# The purpose of this file is for automated testing of dotfiles installation, #
# workstation setup, and updating. It'ss not meant for testing .bash_profile  #                                         #
###############################################################################
language: bash
sudo: required
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      # services: docker
    - os: osx
      osx_image: xcode11.5
      # currently not working with travis :(
      sudo: required

env:
  - TRAVIS_CI_RUN=true GIT_SSH='ssh -o StrictHostKeyChecking=no' GIT_AUTHOR_NAME='Travis CI' GIT_AUTHOR_EMAIL='travis@example.com'

install: true

script:
  - bash -x home/.bootstrap.sh
  - bash -x home/.workstation_setup.sh # in case the trigger (hash git) doesn't trip in .bashrc
  - bash -x home/.workstation_update.sh
# OPTIONAL before_cache (for cleaning up cache)

notifications:
  email:
    on_failure: never
    on_success: never
  # slack: https://docs.travis-ci.com/user/notifications/#Configuring-Slack-notifications
    # secure: a;lsdkjf;lasdkfj
# sudo: required
