#!/bin/bash

# git syntax in prompt
# TODO: use different colors for different datacenters/environments using VLANs
# export PS1="\[\033[01;32m\]\u@\h\[\033[01;34m\] \w\[\033[01;33m\]\[\033[01;34m\] \
#   (\$(git branch 2>/dev/null | grep '^*' | colrm 1 2)) \
#   \$\[\033[00m\] "

# PS1 Codes
# u - the current user's username
# h - the current machine's hostname
# j - the number of jobs managed by this shell
# @ - the current time (12 hour format)
# d - the current date
# w - path of the current working directory
# W - just the current working directory
# e - an ASCII escape character (033)
# n - adds a newline character

# using github.com/nojhan/liquidprompt for PS1 customizations
if [[ -f /usr/local/share/liquidprompt ]]; then
  . /usr/local/share/liquidprompt
fi

# more PS1 colors
NORMAL=$(tput sgr0)
BLINK=$(tput blink)
BRIGHT=$(tput bold)
WHITE=$(tput setaf 7)
RED_BG=$(tput setab 1)
YELLOW=$(tput setaf 3)

__kube_ps1() {
  # get kubernetes context and namespace info
  # http://blog.cloud66.com/kubernetes-and-gcloud-bash-prompts/
  # https://gist.github.com/seanknox/c42e77b189678cbddd3c347e5816a152
  export K8S_CONTEXT=$(kubectl config current-context 2> /dev/null || '')
  export K8S_NS=$(kubectl config view ${K8S_CONTEXT} \
    --output json | jq ".contexts[] | select(.name==\"${K8S_CONTEXT}\") | .context.namespace" | tr -d '"' || '')
  if [[ -n ${K8S_CONTEXT} ]]; then
    if [[ "${K8S_CONTEXT}" =~ "dam" ]]; then
      echo -e "${BRIGHT}${WHITE}${RED_BG}${BLINK}${K8S_CONTEXT%%.*}:${K8S_NS}${NORMAL} "
    else
      echo -e "${YELLOW}${K8S_CONTEXT%%.*}:${K8S_NS}${NORMAL} "
    fi
  fi
}

LP_PS1_PREFIX="$(__kube_ps1)"
